"""Recreate missing migrations

Revision ID: 13af215aa15b
Revises: e92efd8f1094
Create Date: 2024-10-15 15:20:36.429849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13af215aa15b'
down_revision = 'e92efd8f1094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
