"""empty message

Revision ID: 24056189189a
Revises: 13af215aa15b
Create Date: 2024-10-18 12:25:56.997380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24056189189a'
down_revision = '13af215aa15b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notification_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('sent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(length=255), server_default=sa.text("'No message provided'::character varying"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'unread'::character varying"), autoincrement=False, nullable=True),
    sa.Column('trigger_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name='notifications_subscription_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    # ### end Alembic commands ###
